### ISSUE TITLE
When I connect my Limit switch machine shuts down. When switch is pressed comes on

### ISSUE THREAD

**Issue by growlybearproductions** [makerbase-mks/MKS-DLC32#266]
I don't know if this is a hardware or software issue. The switch has an LED. When switch is engaged the LED comes on

When switch is NOT engaged the system only has the main power light Everything else shuts off. If I press the switch all lights come back on.

**Comment by keithstrachan** [comment]
what it seems like is that your pins are not matching up and you have a short.
I would disconnect them to prevent any damage to your board, and then you need to check your wiring for your switches.

many of the limit switches have pins swapped around because they're wired for RAMPS boards. You need to make sure that GND from the switch, comes to GND on the DLC board, voltage to voltage, signal to signal.

the wiring manual located [here](https://github.com/makerbase-mks/MKS-DLC32/blob/main/doc/DLC32%20wiring%20manual.pdf)
is quite easy to understand and follow.

good luck.
