### ISSUE TITLE
Hardware problem: pin enable is always up

### ISSUE THREAD

**Issue by xorkrus** [makerbase-mks/MKS-DLC32#271]
Such a problem. on the drivers, the enable pin is always up and control does not occur.
I tried to change 74hc595 but the problem remained. I removed the esp32 from the board, but the enable pin is still up. without 74hc595 switch enable pin down. checked 595 all working. I bought 2 more new 595 and with them the enable pin is always up. what is the problem?

**Comment by abinoer** [comment]
When you remove esp32, the high level of the enable pin is normal, because there is a pull-up resistance. If it is confirmed that the board has successfully burned the firmware or the motor cannot be controlled, there may be something wrong with the hardware, please contact the after-sales service to solve it
