### ISSUE TITLE
Fan output

### ISSUE THREAD

**Issue by Anderson8153** [makerbase-mks/MKS-DLC32#39]
How could it be done to control a fan in place of the Z axis or other output?

**Comment by 21mac** [comment]
to control it via Z axis output is quite difficult since it's not just a power output pin but a controller for a bldc motor.
Why don't you just plug the fan into the 12 Volt port? so the fan would be on full speed as long as the board is turned on.

There is no "easy" solution to control the fans speed via an output pin.

**Comment by Anderson8153** [comment]
@21mac , Hi, I understand, I just want to turn the fan on and off via Gcode

**Comment by 21mac** [comment]
I don't think that will work.
Since - as I meantioned- there is not output pin (from the microcontroller ESP32) which connects to a controllable pin for the fan, there is not Gcode for it.

The board only has one ttl (= PWM) port which is reserved for the laser.
The other ports/sockets are for the motors, the spindle, the end switches or are just power pins (12V, 24V).

There is not possibility to turn these ports on/off.


only in one scenario it will work: if you dont use the ttl (PWM) port for a laser.
- which board (1.0, 1.1, 2.0, 2.1) do you have?
- do you use a laser module or a cnc spindle motor?
- how did you connect everything? can you upload a picture of your board with all cables connected?

**Comment by 21mac** [comment]
I don't think that will work.
Since - as I meantioned- there is not output pin (from the microcontroller ESP32) which connects to a controllable pin for the fan, there is not Gcode for it.

The board only has one ttl (= PWM) port which is reserved for the laser.
The other ports/sockets are for the motors, the spindle, the end switches or are just power pins (12V, 24V).

There is not possibility to turn these ports on/off.


only in one scenario it will work: if you dont use the ttl (PWM) port for a laser.
- which board (1.0, 1.1, 2.0, 2.1) do you have?
- do you use a laser module or a cnc spindle motor?
- how did you connect everything? can you upload a picture of your board with all cables connected?

**Comment by Anderson8153** [comment]
@21mac , 2.0 board with laser module, connected to TTL output.

I connected the fan to one of the 12/24V outputs and installed a switch

![WhatsApp Image 2021-11-19 at 17 22 45](https://user-images.githubusercontent.com/27018751/142687965-63114772-bedd-481b-978b-5389a6c6a394.jpeg)
![WhatsApp Image 2021-11-19 at 17 23 14](https://user-images.githubusercontent.com/27018751/142687971-6a7c5bdd-c21e-49f9-a125-3bdea62aa2e5.jpeg)
![WhatsApp Image 2021-11-19 at 17 25 07](https://user-images.githubusercontent.com/27018751/142687972-32b9052b-9a77-44a9-8899-9145f341b21f.jpeg)

**Comment by 21mac** [comment]
> @21mac , 2.0 board with laser module, connected to TTL output.
> 
> I connected the fan to one of the 12/24V outputs and installed a switch
> 
> ![WhatsApp Image 2021-11-19 at 17 22 45](https://user-images.githubusercontent.com/27018751/142687965-63114772-bedd-481b-978b-5389a6c6a394.jpeg) ![WhatsApp Image 2021-11-19 at 17 23 14](https://user-images.githubusercontent.com/27018751/142687971-6a7c5bdd-c21e-49f9-a125-3bdea62aa2e5.jpeg) ![WhatsApp Image 2021-11-19 at 17 25 07](https://user-images.githubusercontent.com/27018751/142687972-32b9052b-9a77-44a9-8899-9145f341b21f.jpeg)

Damn. there is no other software / Gcode controllable port, just the ttl.
Since the firmware is not open source there is no way to use another pin of the ESP32.

sorry

**Comment by Anderson8153** [comment]
@21mac , Don't worry, thanks for the help!

**Comment by makerbase-mks** [comment]
Sorry, as 21mac said, now there is no method.
