### ISSUE TITLE
Unable to update with any firmware

### ISSUE THREAD

**Issue by steersteer** [makerbase-mks/MKS-DLC32#495]
Hi,
I'm now on 6 hours attempting to get this board to do anything.
I initially started with the WiFi set-up, it appeared to work but nothing showed up on my network.
I decided to get the latest firmware and this is all that happens:
![image](https://github.com/user-attachments/assets/bd3186bd-d93d-4ac4-b9ef-59a7347b8364)

Any ideas?

**Comment by meistertek** [comment]
> Hi, I'm now on 6 hours attempting to get this board to do anything. I initially started with the WiFi set-up, it appeared to work but nothing showed up on my network. I decided to get the latest firmware and this is all that happens: 
> 
> Any ideas?

@steersteer This messed me up for quite a few hours as well! There is a mistake in the document that guides you through the process of using the MKS Firmware Tool, the ESP32 chip is not standard and has 8MB of flash memory. If you select FLASH SIZE: 8MB (or 16MB) the firmware loads into the board and also the touchscreen works instead of being blank. I figured this out by viewing this helpful youtube video by Mani Fa: [MKS DLC32 and TS35-R](https://youtu.be/Qz-weOHobjk?feature=shared)

Here is the screen shot that shows the correct setting for the flash tool:
![MKS DLC32 2024](https://github.com/user-attachments/assets/2ab2bd13-7367-4ff6-82f0-7a363d0dbbdc)  

Hope this helps!

**Comment by steersteer** [comment]
Thanks for that. 
It didn't initially work for me but I changed usb cable and bingo! I'm all up and running now.
Just have to work out my fluidNC issues now

**Comment by JSF9026** [comment]
can you please share the bin file or the link to download it ?
